### ISSUE TITLE
[Feature Request] Add colour picker

### ISSUE THREAD

**Issue by lionirdeadman** [lainsce/emulsion#1]
When trying to make a new palette, I find it helpful to be able to simply select the colours.

Currently this would mean using a colour picker tool and putting the values back into emulsion.

**Comment by lainsce** [comment]
This is in the works for Emulsion 2.0

**Comment by lainsce** [comment]
This will need some external help due to flatpak portals, of which I don't know how to code with.

**Comment by lainsce** [comment]
Fixed finally.
