### ISSUE TITLE
Phantom padding around the app window.

### ISSUE THREAD

**Issue by AbrarSL** [lainsce/emulsion#18]
There seems to be some sort of phantom padding around the window border. It shows up when maximized or when the window is pressed against the edges in gnome-shell.

The app version is 3.2.0

![Screenshot of the issue.](https://user-images.githubusercontent.com/69783006/143868319-32ca5e3c-7eac-45b5-aa9f-c7b50629b066.png)

**Comment by lainsce** [comment]
I'll look into this.
