### ISSUE TITLE
Emulsion won't remeber palettes

### ISSUE THREAD

**Issue by stpnwf** [lainsce/emulsion#2]
Emulsion won't save edits I make to palettes I create, and is a bit glitchy. I am unable to change/remove colors. I have included a gif showing the issue.
I couldn't get Screenkey set up, but the only keys I press (other than typing "Green") are Ctrl + C and Crtl + V when pasting Hex codes from gedit into Emulsion.

I am running version 2.0.0 installed from Flathub.

![screenrec](https://user-images.githubusercontent.com/81482539/122655507-4d4ef900-d142-11eb-89f5-4ccaf5b2a219.gif)

**Comment by lainsce** [comment]
There's a thing with entries, that to actually save things done with them, one needs to press enter to confirm. Before when I was using GTK3, a user indeed could just ctrl-V something and it wouldn't require a enter, but now with GTK4, one needs to press enter.

**Comment by stpnwf** [comment]
Okay, doing so saved my palette, thank you. Opening the palette still shows a black screen afterwards though, reopening the application seems to pause that behavior.
Given that limitation, may I suggest the addition of a Save button inside the palette to save changes? Current behavior can be very annoying to many users.

Also, (I will put this in a separate issue), but given how I would like to create a palette with similar colors, it occurred to me that it would be helpful to be able to name/label the colors so that I can know which colors are which. Reordering colors would be very helpful as well.

**Comment by lainsce** [comment]
I'll look into how to best place the save button.

**Comment by lainsce** [comment]
I've looked into this, and, it seems that all I need to do to fix this is to update the flatpak in flathub to point to newer dependency commits. I'll do this once I code the Colour Picker function and other stuff from the other issues.
