### ISSUE TITLE
[Bug] Palettes extracted from images don't show up immediately.

### ISSUE THREAD

**Issue by AbrarSL** [lainsce/emulsion#25]
Emulsion v3.2.0 from Flathub.
I didn't use the keyboard so I didn't use Screenkey.

https://user-images.githubusercontent.com/69783006/144696625-8f536b10-24fb-4bc8-bb98-2987a7921b1c.mp4

**Comment by lainsce** [comment]
Fixed, will come in the next release in 2022.
