### ISSUE TITLE
[Feature Request] Name colors / Reorder colors

### ISSUE THREAD

**Issue by stpnwf** [lainsce/emulsion#3]
Hey, these are some feature suggestions that I feel could make this app even better.

1. Ability to name/label colors in palettes. This can be very useful when doing palettes of similar colors.
2. Ability to reorder colors in palettes. This can be useful to compare colors side by side to pick the best fit.
3. Ability to double click the color or the area the Hex is displayed to copy the Hex value to the clipboard.
4. Currently dragging the RBG channels will not update the color that is displayed. Could the color be updated live as the RGB channels are changed?

**Comment by lainsce** [comment]
I'll look into these 4 things soon™

**Comment by lainsce** [comment]
Here I am again, I'll reply to each number:
> 1. Ability to name/label colors in palettes. This can be very useful when doing palettes of similar colors.
This can be done, I'll just need to make the UI and logic behind so that it doesn't explode lol

> 2. Ability to reorder colors in palettes. This can be useful to compare colors side by side to pick the best fit.
Reordering would require drag-n-drop, I would need to look up how it's done on GTK4

> 3. Ability to double click the color or the area the Hex is displayed to copy the Hex value to the clipboard.
This might be a thing the duplicates behaviour, try copying the colour from the three-dot menu.

> 4. Currently dragging the RGB channels will not update the color that is displayed. Could the color be updated live as the RGB channels are changed?
This requires some help to be done because I don't know how it would even happen in real time given what I know about the underlying code.

**Comment by lainsce** [comment]
This has become more than I can do. I'm willing to reset what I already did, and let someone else help. :(

**Comment by stpnwf** [comment]
Thanks for giving it a try! I lack the knowledge to help unfortunately, so I can't be of much help.

**Comment by lainsce** [comment]
The main roadblock I've encountered is pairing colors with their names, without a key:value array thing in Vala, this is important to have something like "#FFFFFF:White" which then I could pair in the UI without the sorter moving it.

**Comment by lainsce** [comment]
So here's the deal:

I got named colors to work, _BUT_ I can't have manual sorting of the colors. Hence why I'm closing this issue.
