### ISSUE TITLE
Include the Bootstrap palette

### ISSUE THREAD

**Issue by vanillajonathan** [lainsce/emulsion#33]
https://getbootstrap.com/docs/5.1/customize/color/#all-colors

**Comment by lainsce** [comment]
The palettes I include by default are just examples, you can add this palette yourself if you need to.

**Comment by vanillajonathan** [comment]
Yes, but then I have to add it myself, which takes time and I might unsure how to do so. It would be great if it was already included by default, it would make it more user friendly and quick to get started with.

**Comment by lainsce** [comment]
I could add just the main colors but not the color-xxx ones; otherwise the color code to add this palette would be massive and unmaintainable..

**Comment by vanillajonathan** [comment]
Alright, sounds better than nothing.
