### ISSUE TITLE
[Bug] Selecting a palette is very hit-and-miss

### ISSUE THREAD

**Issue by tcitworld** [lainsce/emulsion#39]
## Description
After creating a new palette, renaming it and going back to the list of palettes, I can't open it anymore. Opening pre-defined palettes still works.

## Video
https://user-images.githubusercontent.com/2197836/164302464-c6b7e564-4905-45fc-a72d-378138074392.mp4

## Versions
Emulsion 3.2.3 installed through Flathub
Fedora 36

## Logs
<details>
<pre>
<code>
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.170: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.170: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.176: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.176: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.181: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.181: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.185: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.185: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.187: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.187: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.189: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.189: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.191: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.191: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.192: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.192: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.194: json_builder_set_member_name: assertion 'member_name != NULL' failed
(io.github.lainsce.Emulsion:2): Json-CRITICAL **: 20:49:42.194: json_builder_add_string_value: assertion 'json_builder_is_valid_add_mode (builder)' failed
</code>
</pre>
</details>

**Comment by lainsce** [comment]
The selection is a bit finnicky, but if you notice, the selection grey ring must be on the palette you chose for it to open.

**Comment by lainsce** [comment]
I didn't have time this cycle to rewrite the backend and views to the new way as seen on Notejot & Khronos, but I will do so in the next cycle, and it'll fix this finnickiness.

**Comment by lainsce** [comment]
Fixed
