### ISSUE TITLE
Some strings in window.ui are untranslatable

### ISSUE THREAD

**Issue by oscfdezdz** [lainsce/emulsion#4]
To be more precise, strings between `<![CDATA[]]>`.

**Comment by lainsce** [comment]
I thik those should be translatable once I update the pot file? The CDATA part should be just a model template for things so it might be hard to translate, idk...

**Comment by oscfdezdz** [comment]
I tried compiling the pot file with meson but they don't show up.

**Comment by lainsce** [comment]
I don't know how to help with this since the CDATA part is meant to be a model/template and I lack the knowledge to make it translatable.

**Comment by oscfdezdz** [comment]
A workaround is to manually add the lines:

```
#: data/ui/window.ui:210
msgid "Copy Palette to Clipboard"
msgstr ""

#: data/ui/window.ui:214
msgid "Copy Palette Image to Clipboard"
msgstr ""

#: data/ui/window.ui:220
msgid "Remove Palette"
msgstr ""
```
...
```
#: data/ui/window.ui:349
msgid "Copy Hexcode to Clipboard"
msgstr ""

#: data/ui/window.ui:353
msgid "Copy RGB to Clipboard"
msgstr ""

#: data/ui/window.ui:359
msgid "Remove Color from Palette"
msgstr ""
```

but it requires modifying the line number each time there is a change in the code. Tested locally and it works as it should.

**Comment by lainsce** [comment]
Could you make a PR for this then? You'd help translators :D

**Comment by lainsce** [comment]
The PR fixed this.
