### ISSUE TITLE
Add palette generator

### ISSUE THREAD

**Issue by rothgar** [lainsce/emulsion#46]
Would it be possible to add color palette generator option to emulsion? I'm color blind and frequently have to generate palettes from sites like https://coolors.co/ using a starter hex value.

It would be a great addition to emulsion if it could do that for me offline and save the palettes it generates.

I would be happy to sponsor some of this work if it's something you'd be willing to work on.

**Comment by rothgar** [comment]
I just discovered your colorway app. Maybe that'll be good enough for what I need. I'll give it a try.

**Comment by lainsce** [comment]
Yup, Colorway is more what you're asking for :P

Closing issue :)
