### ISSUE TITLE
SVG palette export

### ISSUE THREAD

**Issue by difrkaguilar** [lainsce/emulsion#7]
Hello. 

I am graphic designer and I found your app very useful in combination with other open source tools.
Currently I'm using emulsion 2.0.1 version downloaded from Flathub. It will be great if you can add an option to export the palette as .SVG File to work with it for instance in apps like darkatable or Inkscape.

Thanks a lot for this great app.

**Comment by lainsce** [comment]
You can export it as PNG which you could put on a corner of the other app's canvas, is that lacking for you? :thinking:

**Comment by difrkaguilar** [comment]
Nop, .png is ok then. Thanks.
